# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170526_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='delete_track',
            field=models.BooleanField(default=False),
        ),
    ]
