# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_delete_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='delete_track',
        ),
    ]
